on: [push, pull_request]
name: Test and coverage
jobs:
  test-and-coverage:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version-file: './go.mod'
    - name: Tests
      run: make tests
    - name: Tests with race detection
      run: make tests_race
    - name: Build CLI app
      run: make build_cli
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
