on: [push, pull_request]
name: Test and coverage
jobs:
  test-and-coverage:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version-file: './go.mod'
    - name: Test
      run: go test ./...
    - name: Test with race detection
      run: go test -race -covermode atomic -coverprofile coverage.out
    - name: Build CLI app
      run: make build_cli
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
